# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  host: localhost
  adapter: mysql
  database: easy_chat_development
  username: root
  password: admin
  timeout: 5000
  reconnect: false
  charset: utf8
  socket: /var/lib/mysql/mysql.sock


